<?php

/**
 * @file
 * Code for the eReol Video feature.
 */

include_once 'ereol_video.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function ereol_video_entity_info_alter(&$entity_info) {
  $entity_info['file']['view modes'] += array(
    'video_frontpage' => array(
      'label' => t('Video on frontpage'),
      'custom settings' => TRUE,
    ),
    'video_show' => array(
      'label' => t('Video player'),
      'custom settings' => TRUE,
    ),
  );
}

/**
 * Implements hook_menu().
 */
function ereol_video_menu() {
  $items = array();

  $items['video/%node/view'] = array(
    'page callback' => 'ereol_video_view_video',
    'page arguments' => array(1),
    'delivery callback' => 'ajax_deliver',
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Implements hook_preprocess_node().
 */
function ereol_video_preprocess_node(&$variables) {
  $node = $variables['node'];

  if ($node->type == "video" && $variables['view_mode'] == 'teaser') {
    drupal_add_library('system', 'drupal.ajax');
    $variables['link'] = 'video/' . $node->nid . '/view';
  }
}

/**
 * View a video from modal.
 *
 * @param object $node
 *   The video node.
 *
 * @return array
 *   Ajax render array.
 */
function ereol_video_view_video($node) {
  $commands = array();
  $commands[] = ajax_command_ding_popup('ereol_video', t('View video'), drupal_render(node_view($node, 'full')), array('refresh' => TRUE, 'class' => array('video-modal')));

  return array('#type' => 'ajax', '#commands' => $commands);
}

/**
 * Implements hook_preprocess_entity().
 */
function ereol_video_preprocess_entity(&$variables) {
  if ('paragraphs_item' === $variables['entity_type']
  && 'video_bundle' === $variables['paragraphs_item']->bundle()) {
    $wrapper = $variables['paragraphs_item']->wrapper();

    $color = $wrapper->field_link_color->value();
    $variables['classes_array'][] = 'video-bundle-colored';
    // Use #ffffff as background color if none selected.
    $variables['classes_array'][] = '#000000' === reol_base_get_contrast_color($color['rgb'] ?? '#ffffff') ? 'video-bundle-color-dark' : 'video-bundle-color-light';
    if (isset($color['rgb'])) {
      $variables['attributes_array']['style'] = 'background-color: ' . $color['rgb'] . ';';
    }

    // If we have no promoted materials and have a search string, we build a
    // list of promoted materials from the search string.
    if (!isset($variables['content']['field_video_bundle_materials'])
      && $search = trim($wrapper->field_search_string->value())) {
      $max_number_of_items = 4;
      // Execute query and get object ids.
      // Note: Rather than passing ['collectionType' => 'manifestation'] to
      // opensearch_do_search we get all ids from the returned collections to
      // make sure that works (i.e. related ebooks and audio books) are shown
      // together.
      $result = opensearch_do_search($search, 1, $max_number_of_items, [
        'reply_only' => TRUE,
      ]);
      $entity_ids = [];
      foreach ($result->collections as $collection) {
        if (isset($collection->objects) && is_array($collection->objects)) {
          foreach ($collection->objects as $object) {
            $id = $object->id;
            $object = ting_object_load($id);
            if ($object) {
              $entity_id = $object->tid;
              if (!in_array($entity_id, $entity_ids)) {
                $entity_ids[] = $entity_id;
              }
            }
          }
        }
      }

      $entity_ids = array_slice($entity_ids, 0, $max_number_of_items);

      // Render the materials if any.
      if (!empty($entity_ids)) {
        $variables['content']['field_video_bundle_materials'] = [
          '#theme' => 'field',
          '#bundle' => 'ereol_video',
          '#label_display' => 'hidden',
          '#field_name' => 'field_video_bundle_materials',
          '#field_type' => 'ting_reference',
        ];
        foreach ($entity_ids as $delta => $entity_id) {
          $variables['content']['field_video_bundle_materials']['#items'][] = $delta;
          $variables['content']['field_video_bundle_materials'][$delta] = [
            '#theme' => 'ting_reference_item',
            '#entity_id' => $entity_id,
            '#view_mode' => 'teaser',
          ];
        }

        // Add JavaScript to make the material display work.
        drupal_add_js(drupal_get_path('module', 'ting_reference') . '/js/ting_reference_ajax.js');
      }
    }
  }
}
