<?php

/**
 * @file
 * Add eReolen support.
 */

// Required to load form with fields.
module_load_include('inc', 'ereolen_support', 'ereolen_support.form');
module_load_include('inc', 'ereolen_support', 'ereolen_material.form');

/**
 * Implements hook_menu().
 */
function ereol_support_menu() {
  $items['admin/config/ereolen/support'] = [
    'title' => 'eReolen support configuration',
    'description' => 'Administer eReolen support form',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['ereol_support_config_form'],
    'access arguments' => ['alter ereol support form fields'],
    'file' => 'ereol_support.admin.form.inc',
  ];

  $items['support-formular'] = [
    'title' => 'eReolen support',
    'description' => 'eReolen support form',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['ereol_support_form'],
    'file' => 'ereol_support.form.inc',
    'access callback' => TRUE,
  ];

  $items['materialevalg-formular'] = [
    'title' => 'eReolen materialevalg',
    'description' => 'eReolen materialevalg',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['ereolen_material_form'],
    'file' => 'ereolen_material.form.inc',
    'access callback' => TRUE,
  ];

  return $items;
}

/**
 * Implements hook_permission().
 */
function ereol_support_permission() {
  return [
    'administer ereol support form' => [
      'title' => t('Administer ereolen support form'),
    ],
    'alter ereol support form fields' => [
      'title' => t('Alter ereolen support form fields'),
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function ereol_support_mail($key, &$message, $params) {
  switch ($key) {
    case 'ereol_support_publizon_support':
      global $user;
      $params['subject'] = t('Form submission from support form');
      $message['subject'] = $params['subject'];
      $message['body'][] = theme('ereol_support_mail_publizon', [
        'form_input' => $message['params']['form_state']['input'],
        'user' => $user,
        'time' => format_date(time(), 'long'),
      ]);
      break;
  }
}

/**
 * Implements hook_theme().
 */
function ereol_support_theme($existing, $type, $theme, $path) {
  return [
    'ereol_support_mail_publizon' => [
      'variables' => [
        'form_input' => NULL,
        'user' => NULL,
        'time' => NULL,
      ],
      'template' => 'ereol-support--mail-publizon',
      'path' => $path . '/templates/',
    ],
    'ereol_support_help_text' => [
      'variables' => [
        'problem_values' => NULL,
      ],
      'template' => 'ereol-support--help-text',
      'path' => $path . '/templates/',
    ],
    'ereolen_support_lead_text' => [
      'variables' => [
        'text' => NULL,
      ],
      'template' => 'ereolen-support--lead-text',
      'path' => $path . '/templates/'
    ]
  ];
}

/**
 * Implements hook_cron().
 */
function ereol_support_cron() {
  _ereol_support_cleanup_errors();
}
