<?php

/**
 * @file
 * Base functionality for eReolen.
 */

/**
 * Implements hook_form_alter().
 *
 * Change/remove DDB things from forms.
 */
function ereol_base_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'ding_loan_loans_form':
      // Remove "Renew" actions from the loans form.
      unset($form['actions_container']);
      unset($form['#submit']);
      break;
  }
}

/**
 * Implements hook_preprocess_HOOK() for menu_link().
 */
function ereol_base_preprocess_menu_link(&$variables) {
  $element = &$variables['element'];
  if (isset($element['#original_link']) && $element['#original_link']['menu_name'] == 'main-menu') {
    // Login icon.
    if ($element['#original_link']['router_path'] == 'login/nojs') {
      $element['#localized_options']['attributes']['class'][] = 'user-login-link';
    }

    // Logged in icon.
    if ($element['#original_link']['router_path'] == 'user') {
      $element['#localized_options']['attributes']['class'][] = 'user-logged-in-link';
    }
  }
}

/**
 * Implements hook_field_default_field_instances_alter().
 */
function ereol_base_field_default_field_instances_alter(&$fields) {
  if (isset($fields['ting_object-ting_object-ting_details_language'])) {
    // Show language in "compact" view.
    $fields['ting_object-ting_object-ting_details_language']['display']['compact'] = [
      'label' => 'hidden',
      'module' => 'ting_material_details',
      'settings' => array(),
      'type' => 'ting_details_single',
      'weight' => 1,
    ];
  }

  // Move cover before details_language.
  if (isset($fields['ting_object-ting_object-ting_cover'])) {
    $fields['ting_object-ting_object-ting_cover']['display']['compact']['weight'] = 0;
  }

  // Hide material type.
  if (isset($fields['ting_object-ting_object-ting_details_type'])) {
    $fields['ting_object-ting_object-ting_details_type']['display']['compact'] = [
      'label' => 'hidden',
      'module' => 'ting_material_details',
      'settings' => array(),
      'type' => 'hidden',
      'weight' => 6,
    ];
  }
}
