<?php

/**
 * @file
 * Base functionality for eReolen.
 */

/**
 * Implements hook_form_alter().
 *
 * Change/remove DDB things from forms.
 */
function ereol_base_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'user_login':
    case 'user_login_block':
      // Remove the Ajax part of the form to prevent 2x pop-ups.
      unset($form['user_login_container']['actions']['submit']['#ajax']);
      break;

    case 'ding_loan_loans_form':
      // Remove "Renew" actions from the loans form.
      unset($form['actions_container']);
      unset($form['#submit']);
      break;
  }
}

/**
 * Implements hook_field_default_field_instances_alter().
 */
function ereol_base_field_default_field_instances_alter(&$fields) {
  if (isset($fields['ting_object-ting_object-ting_details_language'])) {
    // Show language in "compact" view.
    $fields['ting_object-ting_object-ting_details_language']['display']['compact'] = [
      'label' => 'hidden',
      'module' => 'ting_material_details',
      'settings' => array(),
      'type' => 'ting_details_single',
      'weight' => 1,
    ];
  }

  // Move cover before details_language.
  if (isset($fields['ting_object-ting_object-ting_cover'])) {
    $fields['ting_object-ting_object-ting_cover']['display']['compact']['weight'] = 0;
  }

  // Hide material type.
  if (isset($fields['ting_object-ting_object-ting_details_type'])) {
    $fields['ting_object-ting_object-ting_details_type']['display']['compact'] = [
      'label' => 'hidden',
      'module' => 'ting_material_details',
      'settings' => array(),
      'type' => 'hidden',
      'weight' => 6,
    ];
  }
}
